### ISSUE TITLE
Running example_counter failed

### ISSUE THREAD

**Issue by ibaaj** [CanalTP/libosmpbfreader#1]
OSX 10.10 Yosemite
protobuf 2.6.1
osm-pbf 1.3.3

Made examples without error :

```
g++ -O3 -std=c++0x -Wall -Wextra -o example_routing example_routing.cc -lprotobuf-lite -losmpbf -lz 
g++ -O3 -std=c++0x -Wall -Wextra -o example_counter example_counter.cc -lprotobuf-lite -losmpbf -lz
```

then tried to run examples... : 

```
   ./example_counter /path/to/my/osmfile.osm 
   [INFO] Reading the file/path/to/my/osmfile.osm
   [FATAL] blob-header-size is bigger then allowed 1010792557 > 65536
```

Tried to edit this line in osmpbfreader.h

```
const int max_blob_header_size = 64 * 1024; // 64 kB
```

increased the value (1024^3). But exited with error code status : 11

**Comment by TeXitoi** [comment]
Can we see your osmfile.osm? note that this library can only read pbf files, not osm xml files. I suspect that your file is a xml or a gzipped xml.

**Comment by ibaaj** [comment]
I just converted it in pbf format then it is working, sorry for inconvenient..

**Comment by TeXitoi** [comment]
No problem. Enjoy the lib :smile:
