### ISSUE TITLE
get data just from spacial extend

### ISSUE THREAD

**Issue by am2222** [CanalTP/libosmpbfreader#2]
Hi,
Is it possible to just read data from an extent? not the whole file?

**Comment by TeXitoi** [comment]
The pbf format is linear, thus you need to read the whole file.

It would be possible to add an option to not decode nodes outside of a bounding box. It's difficult to predict the performance gain, and it's not trivial to implement.

**Comment by am2222** [comment]
@TeXitoi so there is not any way to filter data?for example in every boundry box request all data have to be read?

**Comment by TeXitoi** [comment]
@am2222 exactly, there is no way to filter without reading the data entirely.
