### ISSUE TITLE
Lat and Lons for nodes are only accurate to 3-4 decimal places

### ISSUE THREAD

**Issue by CraigglesO** [CanalTP/libosmpbfreader#5]
Sorry to bother again.

For some reason lon is only accurate to 3 decimal places while lats are 4 decimal places accurate.

Is this normal? When I use a NodeJS implementation, I get accuracy to 7 places. Your implementation looks correct to me. So I don't know why this is happening. Taking geojson of the resultant nodes for both implementations, the nodes line up with maps from JS but not for this C++ implementation, they all line up in rows and columns.

**Comment by TeXitoi** [comment]
Is you `node_callback` taking double or float? float is not enough for lat and lon, maybe the problem come for using float somewhere in your code?

**Comment by CraigglesO** [comment]
No, I am using doubles. I used osmium directly just to check if it was an error in your code... It's not; osmium naturally pulls a smaller precision double for some reason when calling `node.location().lon()`.

Their code uses doubles as well, I don't know what is causing this, but it definitely traces back to their code.

**Comment by TeXitoi** [comment]
OK, sorry to not be so helpful then.
